name: Trigger auto deployment for freddie-bot

# When this action will be executed
on:
    # Automatically trigger it when detected changes in repo
    push:
        branches: [main]
        paths:
            - '**'
            - '.github/workflows/freddie-bot-deploy.yml'

    # Allow manual trigger
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v2

            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.FREDDIEBOT_AZURE_CREDENTIALS }}

            - name: Build and push container image to registry
              uses: azure/container-apps-deploy-action@v2
              with:
                  appSourcePath: ${{ github.workspace }}
                  registryUrl: freddie.azurecr.io
                  registryUsername: ${{ secrets.FREDDIEBOT_REGISTRY_USERNAME }}
                  registryPassword: ${{ secrets.FREDDIEBOT_REGISTRY_PASSWORD }}
                  containerAppName: freddie-bot
                  resourceGroup: freddie-puzzles
                  imageToBuild: freddie.azurecr.io/freddie-bot:${{ github.sha }}
                  dockerfilePath: Dockerfile
